<?php

/**
 * Parser.php object
 *
 * @package    Parser.php
 * @since      2016-09-06
 */

namespace TBoxCronManager;

class Parser implements JobInterface
{

	/*
	example:
	--------
	# BEGIN:some_auto_hash
	# Comment: aceasta este o descriere a jobului
	*	* 	*	*	*	echo "cocorico" >> some_log_file.log
	# END:some_auto_hash
	*/
	private $begin = "# BEGIN:";
	private $end = "# END:";
	private $comment = "# Comment:";
	private $label = "Autogenerated by CrontabManager.";
	
	public function parse(&$data)
	{
		$jobs = array();
		$validJobs = array();
		foreach($data as $lineidx => $line)
		{
			//begin of the def of job
			if(strpos($line,$this->begin) === 0)
			{
				$hash = substr($line, strlen($this->begin));
				$jobs[$hash] = array();
			}

			//end of the def of job
			if(strpos($line,$this->end) === 0)
			{
				$hash = substr($line, strlen($this->end));
				// if the job has begin then we create our object
				if(isset($jobs[$hash]))
				{
					$job = new Job();
					$job->hydrate($this->_parse($data[$lineidx-1]));
					$job->comment(substr($data[$lineidx-2],strlen($this->comment)));

					if(Manager::hash($job) === $hash){
						$validJobs[$hash] = $job;
						// begin line
						unset($data[$lineidx-3]);
						// comment line
						unset($data[$lineidx-2]);
						// job line
						unset($data[$lineidx-1]);
						// end line
						unset($data[$lineidx]);
					}
					unset($job);
				}
			}
		}
		unset($jobs);

		return $validJobs;
	}

	public function prepare(array $Jobs)
	{
		$content = '';
		foreach ($Jobs as $job) 
		{
			$jobsHash = Manager::hash($job);
			$content .= $this->begin . $jobsHash . PHP_EOL . $this->comment . $job->comment . PHP_EOL . $job . PHP_EOL . $this->end . $jobsHash . PHP_EOL;
		}
		$content = trim($content,PHP_EOL);

		return $content;
	}

	 /**
     * Parse crontab line into Job object
     *
     * @param string $jobSpec
     * @return Job
     * @throw \InvalidArgumentException if $jobSpec isn't crontab entry
     */
    private function _parse($jobSpec)
    {
        $regex = '/^\s*(([^\s\#]+)\s+([^\s\#]+)\s+([^\s\#]+)\s+([^\s\#]+)\s+' .
            '([^\s\#]+))\s+([^\#]+)(?:#(.*))?$/';

        preg_match($regex, $jobSpec, $match);    
            
        if (!$match) {
            throw new \InvalidArgumentException('$jobSpec must be crontab compatibile entry');
        }
        list(,,
            $minute,
            $hour,
            $dayOfMonth,
            $month,
            $dayOfWeek,
            $command) = $match;
        /*if (isset($match[8])) {
            $lineComment = $match[8];
            $lineComment = trim($lineComment);
        }*/

        return array(
        	'minute'=>$minute,
            'hour'=>$hour,
            'dayOfMonth'=>$dayOfMonth,
            'month'=>$month,
            'dayOfWeek'=>$dayOfWeek,
            'command'=>$command
        );
    }

}